[[redirects]]
  from   = "/manual-of-me"
  to     = "/me"
  status = 302

[[redirects]]
  from   = "https://me.engiqueer.net/*"
  to     = "https://www.engiqueer.net/me"
  status = 302
  force  = true